### ISSUE TITLE
Roadmap of MMSegmentation

### ISSUE THREAD

**Issue by csatsurnh** [open-mmlab/mmsegmentation#2750]
We keep this issue open to collect feature requests from users and hear your voice. Our monthly release plan is also available here.

You can either:

1. Suggest a new feature by leaving a comment.
2. Vote for a feature request with +1 or be against with -1. (Remember that developers are busy and cannot respond to all feature requests, so vote for your most favorable one!)
3. Tell us that you would like to help implement one of the features in the list or review the PRs. (This is the greatest things to hear about!)

## V0.1.0(2023.1)

- code
    - [ ] Support Hausdorff distance loss (支持 Hausdorff distance loss)
    - [ ] Support boundary loss (支持 boundary loss)
    - [ ] Support SwinV2 (UperNet) model (支持 SwinV2 (UperNet) 模型)
    - [ ] Support TransUnet model (支持 TransUnet 模型)
    - [ ] Add semantic information to segmentation results visualization (分割可视化结果中加上语义信息)
- doc
    - [ ] Zh_CN FAQ documentation migration (中文 FAQ 文档迁移)
    - [ ] EN FAQ documentation migration (英文 FAQ 文档迁移)

**Comment by jediofgever** [comment]
Can you support segfromer in mmdeploy, this network performance very well to my case but the inference time is quite slow.

**Comment by xiexinch** [comment]
## 2023.04  Development plan

- [ ] Merge part of medical image datasets pull requests
- [ ] Support data loading of remote sensing images https://github.com/open-mmlab/mmsegmentation/pull/2903
- [ ] Support DDRNet in main dev-1.x branch https://github.com/open-mmlab/mmsegmentation/pull/2855
